# Name of the Minigame
game-name: SurvivalBrawl
game-description: A minigame where players will be thrown into a survival world, then fight to the death!
command-name: survivalbrawl
command-aliases:
  - sb

countdown: 30
required-players: 2
max-players: 8
lobby-spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
