name: SurvivalBrawl
version: '${project.version}'
main: org.kcsup.survivalbrawl.Main
api-version: 1.8.8
description: A minigame where players will be thrown into a survival world, then fight to the death!
